[package]
name = "gong-playground"
version = "1.0.3"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
An interactive "playground" program for testing out the `gong` library crate's functionality. It
prints analysis of given command line arguments.
"""
publish = false

[[bin]]
name = "gong-playground"
path = "./main.rs"
doc = false

[dependencies]
gong = { path = "../lib" }
term-ctrl = { git = "https://github.com/jnqnfe/term-ctrl-rust", tag = "v0.1" }

[features]
default = []
alt_mode = []
keep_prog_name = []
no_abbreviations = []
