[package]
name = "gong-playground"
version = "1.2.1"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = """
An interactive “playground” program for testing out the `gong` library crate’s functionality. It
prints analysis of given command line arguments.
"""
publish = false
edition = "2018"

[[bin]]
name = "gong-playground"
path = "./main.rs"
doc = false

[dependencies]
gong = { path = "../lib" }
term-ctrl = "0.7"

[features]
default = ["color"]
# See the `README.md` file for documentation of these
alt_mode = []
posixly_correct = []
keep_prog_name = []
no_opt_abbreviations = []
no_stop_on_problem = []
pos_policy2 = []
color = []
